USE LAB3_ACTIVIDAD_3_1

GO
-- A)
CREATE FUNCTION dbo.TotalDebitosxTarjeta(@IDTarjeta BIGINT)
RETURNS MONEY
AS
BEGIN
    DECLARE @TotalDebito MONEY;

    SET @TotalDebito = 0;

    SELECT @TotalDebito = SUM(M.IMPORTE)
    FROM MOVIMIENTOS AS M
    WHERE M.IDTARJETA = @IDTarjeta AND M.TIPO = 'D';

    RETURN @TotalDebito
END

GO
-- B)
CREATE FUNCTION dbo.TotalCreditosxTarjeta(@IDTarjeta BIGINT)
RETURNS MONEY
AS
BEGIN
    DECLARE @TotalCredito MONEY;

    SET @TotalCredito = 0;

    SELECT @TotalCredito = SUM(M.IMPORTE)
    FROM MOVIMIENTOS AS M
    WHERE M.IDTARJETA = @IDTarjeta AND M.TIPO = 'C'

    RETURN @TotalCredito
END

GO
-- C)
CREATE VIEW VW_TARJETAS_USUARIOS AS
SELECT U.APELLIDO, U.NOMBRE, T.IDTARJETA, T.ESTADO, T.SALDO
FROM USUARIOS AS U
INNER JOIN TARJETAS AS T ON T.IDUSUARIO = U.IDUSUARIO

GO
-- D)
CREATE VIEW VW_VIAJES_USUARIOS AS
SELECT U.APELLIDO, U.NOMBRE, T.IDTARJETA, V.FECHA, V.IMPORTE, V.NRO_INTERNO, L.NOMBRE AS NOMBRE_LINEA
FROM USUARIOS AS U
INNER JOIN TARJETAS AS T ON T.IDUSUARIO = U.IDUSUARIO
INNER JOIN VIAJES AS V ON V.IDTARJETA = T.IDTARJETA
INNER JOIN LINEAS AS L ON L.IDLINEA = V.IDLINEA

GO
-- E)
CREATE VIEW VW_ESTADISTICAS_TARJETAS AS
SELECT U.APELLIDO, U.NOMBRE, T.IDTARJETA,
(
    SELECT COUNT(*) FROM VIAJES AS V
    WHERE V.IDTARJETA = T.IDTARJETA
)AS CANTIDAD_VIAJES,
(
    SELECT SUM(M.IMPORTE) FROM MOVIMIENTOS AS M
    WHERE M.IDTARJETA = T.IDTARJETA AND M.TIPO = 'C'
)AS DINERO_ACREDITADO,
(
    SELECT COUNT(*) FROM MOVIMIENTOS AS M
    WHERE M.IDTARJETA = T.IDTARJETA AND M.TIPO = 'C'
)AS CANTIDAD_RECARGA,
(
    SELECT AVG(M.IMPORTE) FROM MOVIMIENTOS AS M
    WHERE M.IDTARJETA = T.IDTARJETA AND M.TIPO = 'C'
)AS RECARGA_PROMEDIO,
T.ESTADO
FROM USUARIOS AS U
INNER JOIN TARJETAS AS T ON T.IDUSUARIO = U.IDUSUARIO
