USE LAB3_ACTIVIDAD_3_1

/* EJERCICIO 2 */
GO
CREATE PROCEDURE sp_Agregar_Tarjeta
(
    @DNI VARCHAR(10)
)
AS
BEGIN

    BEGIN TRY

        BEGIN TRANSACTION

            DECLARE @IDUSUARIO BIGINT;
            DECLARE @TARJETAVIEJA BIGINT;
            DECLARE @SALDO MONEY;

            SELECT @IDUSUARIO = @IDUSUARIO
            FROM USUARIOS
            WHERE @DNI = DNI

            SELECT @TARJETAVIEJA = IDTARJETA, @SALDO = @SALDO
            FROM TARJETAS
            WHERE @IDUSUARIO = IDUSUARIO AND ESTADO = 1

            IF @TARJETAVIEJA IS NOT NULL
            BEGIN
                UPDATE TARJETAS
                SET ESTADO = 0
                WHERE @TARJETAVIEJA = IDTARJETA
            END

            INSERT INTO TARJETAS (IDUSUARIO, FECHA_ALTA, SALDO, ESTADO)
            VALUES (@IDUSUARIO, GETDATE(), ISNULL(@SALDO, 0), 1)
        COMMIT TRANSACTION
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION
        RAISERROR ('SE PRODUJO UN ERROR', 16, 1)
    END CATCH    
END

/* EJERCICIO 3 */
GO
CREATE PROCEDURE sp_Agregar_Viaje
(
    @IDTARJETA BIGINT,
    @IMPORTE SMALLMONEY,
    @NRO_INTERNO BIGINT,
    @IDLINEA BIGINT
)
AS
BEGIN
    BEGIN TRY

        BEGIN TRANSACTION

            DECLARE @SALDOACTUAL MONEY

            SELECT @SALDOACTUAL = SALDO
            FROM TARJETAS
            WHERE @IDTARJETA = IDTARJETA

            IF @SALDOACTUAL - @IMPORTE > -2000
            BEGIN
                UPDATE TARJETAS
                SET SALDO = SALDO - @IMPORTE
                WHERE @IDTARJETA = IDTARJETA

                INSERT INTO VIAJES (FECHA, NRO_INTERNO, IDLINEA, IDTARJETA, IMPORTE)
                VALUES (GETDATE(), @NRO_INTERNO, @IDLINEA, @IDTARJETA, @IMPORTE)

                INSERT INTO MOVIMIENTOS (FECHA, IDTARJETA, IMPORTE, TIPO)
                VALUES (GETDATE(), @IDTARJETA, @IMPORTE, 'D')
            END
        COMMIT TRANSACTION
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION
        RAISERROR ('EL SALDO NEGATIVO ES MAYOR A -2000', 16, 1)
    END CATCH
END

/* EJERCICIO 4 */
GO
CREATE PROCEDURE sp_Agregar_Saldo
(
    @IDTARJETA BIGINT,
    @SALDOACARGAR MONEY
)
AS
BEGIN
    BEGIN TRY

        BEGIN TRANSACTION

            IF EXISTS (SELECT * FROM TARJETAS WHERE @IDTARJETA = IDTARJETA)
            BEGIN
                UPDATE TARJETAS SET SALDO = SALDO + @SALDOACARGAR
                WHERE @IDTARJETA = IDTARJETA

                INSERT INTO MOVIMIENTOS (FECHA, IDTARJETA, IMPORTE, TIPO)
                VALUES (GETDATE(), @IDTARJETA, @SALDOACARGAR, 'C')
            END
        COMMIT TRANSACTION
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION
        RAISERROR ('NO SE ENCUENTRA LA TARJETA INGRESADA', 16, 1)
    END CATCH    
END

/* EJERCICIO 5 */
GO
CREATE PROCEDURE sp_Baja_Fisica_Usuario
(
    @IDUSUARIO BIGINT
)
AS
BEGIN
    BEGIN TRY

        BEGIN TRANSACTION

            IF EXISTS (SELECT * FROM USUARIOS WHERE @IDUSUARIO = IDUSUARIO)
            BEGIN
                DECLARE @IDTARJETA BIGINT

                SELECT @IDTARJETA = @IDTARJETA
                FROM TARJETAS
                WHERE @IDUSUARIO = IDUSUARIO

                DELETE FROM VIAJES 
                WHERE @IDTARJETA = IDTARJETA

                DELETE FROM MOVIMIENTOS
                WHERE  @IDTARJETA = IDTARJETA

                DELETE FROM TARJETAS
                WHERE @IDUSUARIO = IDUSUARIO

                DELETE FROM USUARIOS
                WHERE @IDUSUARIO = IDUSUARIO
            END
        COMMIT TRANSACTION    
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION
        RAISERROR ('ERROR NO SE ENCUENTRA EL ID INGRESADO', 16, 1)
    END CATCH
END